title: Yun Wang's Blog
description: My thoughts, ideas, and experiences
author: Yun Wang
url: https://wangyunai.github.io
baseurl: "/YunWang-Blog"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md 